server:
  port: 0

spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3307/inventory-service
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  application:
    name: inventory-service

  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka
      instance:
        hostname: localhost